### ISSUE TITLE
"DNS Over HTTPS" study is still displayed in "about:addons" page after clicking the "Disable" or "Remove" buttons

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#13]
[Affected versions]:
- Firefox Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" pref set to "true".
- "DNS over HTTPS" add-on is already installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to "about:addons" page, "Extensions" section.
3. Click the "Disable" (or "Remove") button specific to the study and observe what happens next.

[Expected result]:
- "DNS over HTTPS" add-on is no longer displayed in "about:addons" page.

[Actual result]:
- "DNS over HTTPS" add-on is still displayed in "about:addons" page.

[Notes]:
- The expected behavior in this case should be similar to the behavior when disabling the study from the banner or from the study's description page.
- Here is a screen recording of the issue: https://tinyurl.com/ydeqzome

**Comment by jonathanKingston** [comment]
This is an enhancement request. I will need a PM to decide if we should do this. I'm fine with adding it and making it match an uninstall from the disable button.

Using remove should behave the same, is that not the case?

**Comment by SoftVision-PaulOiegas** [comment]
Hey @jonathanKingston, I'm not sure if we got the whole picture here and we want to be 100% sure we are not mistaking. 

Carmen mentioned that the study is removed from `about:addons` when the "Disable DNS Studies" button from the banner is pressed. While, if you manually chose to `Remove` the study from `about:addons` page, it still remains there. 
In our opinion, this is not quite right, but we could be wrong. We have previously tested several studies that were add-ons also and neither of them remained installed after explicitly choosing to "Remove" it from `about:addons` page. 

But, there were variances for the "Disable" button case, where some of them were also removed and some were just disabled and waited to be removed by study end. 
Judging from under the hood behavior, I think in this case the "Disable" button should also uninstall the add-on since "Re-enabling" it, does not change the prefs back to re-enroll the user in the study. Which makes it practically useless...

**Comment by jonathanKingston** [comment]
This should now be fixed with: https://github.com/jonathanKingston/http-dns/pull/4/commits/fa963dc7192783c3c0bc52d6d281a327bbe95d8e

Thanks

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the latest custom build and I can confirm that the add-on is now removed from the "about:addons" page when disabling or removing it.
Also, clicking the "**Disable**" button from "about:addons" changes the next pref values as it follows:
- "network.trr.experimentalRollout" to -3 **_before_** accepting the study from the banner
- "network.trr.experimentalRollout" to -4 **_after_** accepting the study from the banner

- "network.trr.mode" to 0 **_before_** accepting the study from the banner
- "network.trr.mode" to 0 **_after_** accepting the study from the banner

Clicking the "**Remove**" button from "about:addons" changes the next pref values as it follows:
- "network.trr.experimentalRollout" to -2 **_before_** accepting the study from the banner
- "network.trr.experimentalRollout" to -4 **_after_** accepting the study from the banner

- "network.trr.mode" to 0 **_before_** accepting the study from the banner
- "network.trr.mode" to 0 **_after_** accepting the study from the banner
